version: '3.8'

services:
  app:
    build: .
    ports:
      - "6136:4173"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
    environment:
      - NODE_ENV=production
